-- MySQL Script generated by MySQL Workbench
-- Mon Oct  3 09:00:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zal3-zamilab00_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zal3-zamilab00_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zal3-zamilab00_2` DEFAULT CHARACTER SET utf8 ;
USE `zal3-zamilab00_2` ;

-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_compte_cpt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_compte_cpt` (
  `cpt_id` INT NOT NULL AUTO_INCREMENT,
  `cpt_pseudo` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `cpt_mdp` CHAR(64) NOT NULL,
  `cpt_role` CHAR(1) NULL,
  `cpt_etat` CHAR(1) NULL,
  PRIMARY KEY (`cpt_id`),
  UNIQUE INDEX `cpt_pseudo_UNIQUE` (`cpt_pseudo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_profil_pfl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_profil_pfl` (
  `pfl_profil_id` INT NOT NULL AUTO_INCREMENT,
  `pfl_nom` VARCHAR(60) NULL,
  `pfl_prenom` VARCHAR(60) NULL,
  `pfl_mail` VARCHAR(60) NULL,
  `cpt_pseudo` VARCHAR(20) NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`pfl_profil_id`),
  INDEX `fk_t_profil_pfl_t_compte_cpt1_idx` (`cpt_id` ASC),
  CONSTRAINT `fk_t_profil_pfl_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zamilab00_2`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_actualite_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_actualite_act` (
  `act_id` INT NOT NULL AUTO_INCREMENT,
  `act_titre` VARCHAR(60) NULL,
  `act_contenu` VARCHAR(500) NULL,
  `cpt_id` INT NOT NULL,
  `act_date` DATETIME NULL,
  PRIMARY KEY (`act_id`),
  INDEX `fk_t_actualite_act_t_compte_cpt1_idx` (`cpt_id` ASC),
  CONSTRAINT `fk_t_actualite_act_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zamilab00_2`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_quiz_qui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_quiz_qui` (
  `qui_id` INT NOT NULL,
  `qui_illustration` VARCHAR(200) NULL,
  `cpt_id` INT NOT NULL,
  `qui_etat` CHAR(1) NULL,
  PRIMARY KEY (`qui_id`),
  INDEX `fk_t_quiz_t_compte_cpt1_idx` (`cpt_id` ASC),
  CONSTRAINT `fk_t_quiz_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zamilab00_2`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_match_mat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_match_mat` (
  `mat_id` INT NOT NULL AUTO_INCREMENT,
  `mat_date_debut` DATETIME NULL,
  `mat_date_fin` DATETIME NULL,
  `mat_code` CHAR(8) NULL,
  `qui_id` INT NOT NULL,
  `cpt_id` INT NOT NULL,
  `mat_corrige` CHAR(1) NULL,
  PRIMARY KEY (`mat_id`),
  INDEX `fk_t_match_mat_t_quiz1_idx` (`qui_id` ASC),
  INDEX `fk_t_match_mat_t_compte_cpt1_idx` (`cpt_id` ASC),
  CONSTRAINT `fk_t_match_mat_t_quiz1`
    FOREIGN KEY (`qui_id`)
    REFERENCES `zal3-zamilab00_2`.`t_quiz_qui` (`qui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_match_mat_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zamilab00_2`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_joueur_jou`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_joueur_jou` (
  `jou_id` INT NOT NULL AUTO_INCREMENT,
  `jou_pseudo` VARCHAR(45) NULL,
  `mat_id` INT NOT NULL,
  `score` DECIMAL(5,2) NULL,
  PRIMARY KEY (`jou_id`),
  INDEX `fk_t_joueur_jou_t_match_mat1_idx` (`mat_id` ASC),
  CONSTRAINT `fk_t_joueur_jou_t_match_mat1`
    FOREIGN KEY (`mat_id`)
    REFERENCES `zal3-zamilab00_2`.`t_match_mat` (`mat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_question_qst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_question_qst` (
  `qst_id` INT NOT NULL,
  `qst_odre` VARCHAR(45) NULL,
  `qst_intitule_question` VARCHAR(45) NULL,
  `quiz_id` INT NOT NULL,
  PRIMARY KEY (`qst_id`),
  INDEX `fk_t_question_qst_t_quiz1_idx` (`quiz_id` ASC),
  CONSTRAINT `fk_t_question_qst_t_quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `zal3-zamilab00_2`.`t_quiz_qui` (`qui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_reponse_rep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_reponse_rep` (
  `rep_id` INT NOT NULL,
  `rep_texte_reponse` VARCHAR(45) NULL,
  `rep_bonne_reponse` VARCHAR(45) NULL,
  `qst_id` INT NOT NULL,
  PRIMARY KEY (`rep_id`),
  INDEX `fk_t_reponse_rep_t_question_qst1_idx` (`qst_id` ASC),
  CONSTRAINT `fk_t_reponse_rep_t_question_qst1`
    FOREIGN KEY (`qst_id`)
    REFERENCES `zal3-zamilab00_2`.`t_question_qst` (`qst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zamilab00_2`.`t_actualite_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zamilab00_2`.`t_actualite_act` (
  `act_id` INT NOT NULL AUTO_INCREMENT,
  `act_titre` VARCHAR(60) NULL,
  `act_contenu` VARCHAR(500) NULL,
  `cpt_id` INT NOT NULL,
  `act_date` DATETIME NULL,
  PRIMARY KEY (`act_id`),
  INDEX `fk_t_actualite_act_t_compte_cpt1_idx` (`cpt_id` ASC),
  CONSTRAINT `fk_t_actualite_act_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zamilab00_2`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
